/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desktop;

import Logic.GameController;
import Models.Piece;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author jjdelannoy
 */
public class Tablero extends javax.swing.JFrame {
    GameController gameCtrl;
    /**
     * Creates new form Tablero
     */
    public Tablero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPlayer1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPeonX1 = new javax.swing.JTextField();
        txtTorreY1 = new javax.swing.JTextField();
        txtPeonY2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPeonX2 = new javax.swing.JTextField();
        txtPeonY3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPeonX3 = new javax.swing.JTextField();
        txtPeonY4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPeonX4 = new javax.swing.JTextField();
        txtPeonY5 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPeonX5 = new javax.swing.JTextField();
        txtPeonY6 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPeonX6 = new javax.swing.JTextField();
        txtPeonY7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtPeonX7 = new javax.swing.JTextField();
        txtPeonY8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPeonX8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtTorreX1 = new javax.swing.JTextField();
        txtPeonY1 = new javax.swing.JTextField();
        txtTorreY2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtTorreX2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtCaballoX1 = new javax.swing.JTextField();
        txtCaballoY1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCaballoX2 = new javax.swing.JTextField();
        txtCaballoY2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtAlfilX1 = new javax.swing.JTextField();
        txtAlfilY1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtAlfilX2 = new javax.swing.JTextField();
        txtAlfilY2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtReinaX1 = new javax.swing.JTextField();
        txtReinaY1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtReyX1 = new javax.swing.JTextField();
        txtReyY1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtPeonX9 = new javax.swing.JTextField();
        txtPeonY9 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtPeonX10 = new javax.swing.JTextField();
        txtPeonY10 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPeonX11 = new javax.swing.JTextField();
        txtPeonY11 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtPeonX12 = new javax.swing.JTextField();
        txtPeonY12 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtPeonX13 = new javax.swing.JTextField();
        txtPeonY13 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPeonX14 = new javax.swing.JTextField();
        txtPeonY14 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtPeonX15 = new javax.swing.JTextField();
        txtPeonY15 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtPeonX16 = new javax.swing.JTextField();
        txtPeonY16 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        txtTorreX3 = new javax.swing.JTextField();
        txtTorreY3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtTorreX4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtCaballoX3 = new javax.swing.JTextField();
        txtCaballoY3 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtCaballoX4 = new javax.swing.JTextField();
        txtCaballoY4 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtAlfilX3 = new javax.swing.JTextField();
        txtAlfilY3 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtAlfilX4 = new javax.swing.JTextField();
        txtAlfilY4 = new javax.swing.JTextField();
        txtTorreY4 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtReinaX2 = new javax.swing.JTextField();
        txtReinaY2 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtReyX2 = new javax.swing.JTextField();
        txtReyY2 = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Jugador 1");

        jLabel2.setText("Jugador 2");

        jLabel3.setText("Pieza");

        jLabel4.setText("X");

        jLabel5.setText("Y");

        jLabel6.setText("Peon");

        txtPeonX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX1ActionPerformed(evt);
            }
        });

        txtTorreY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreY1ActionPerformed(evt);
            }
        });

        txtPeonY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Peon");

        txtPeonX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX2ActionPerformed(evt);
            }
        });

        txtPeonY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Peon");

        txtPeonX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX3ActionPerformed(evt);
            }
        });

        txtPeonY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY4ActionPerformed(evt);
            }
        });

        jLabel9.setText("Peon");

        txtPeonX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX4ActionPerformed(evt);
            }
        });

        txtPeonY5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY5ActionPerformed(evt);
            }
        });

        jLabel10.setText("Peon");

        txtPeonX5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX5ActionPerformed(evt);
            }
        });

        txtPeonY6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY6ActionPerformed(evt);
            }
        });

        jLabel11.setText("Peon");

        txtPeonX6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX6ActionPerformed(evt);
            }
        });

        txtPeonY7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY7ActionPerformed(evt);
            }
        });

        jLabel12.setText("Peon");

        txtPeonX7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX7ActionPerformed(evt);
            }
        });

        txtPeonY8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY8ActionPerformed(evt);
            }
        });

        jLabel13.setText("Peon");

        txtPeonX8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX8ActionPerformed(evt);
            }
        });

        jLabel14.setText("Pieza");

        jLabel15.setText("X");

        jLabel16.setText("Y");

        jLabel17.setText("Torre");

        txtTorreX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreX1ActionPerformed(evt);
            }
        });

        txtPeonY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY1ActionPerformed(evt);
            }
        });

        txtTorreY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreY2ActionPerformed(evt);
            }
        });

        jLabel18.setText("Torre");

        txtTorreX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreX2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Caballo");

        txtCaballoX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoX1ActionPerformed(evt);
            }
        });

        txtCaballoY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoY1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Caballo");

        txtCaballoX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoX2ActionPerformed(evt);
            }
        });

        txtCaballoY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoY2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Alfil");

        txtAlfilX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilX1ActionPerformed(evt);
            }
        });

        txtAlfilY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilY1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Alfil");

        txtAlfilX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilX2ActionPerformed(evt);
            }
        });

        txtAlfilY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilY2ActionPerformed(evt);
            }
        });

        jLabel23.setText("Reina");

        txtReinaX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReinaX1ActionPerformed(evt);
            }
        });

        txtReinaY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReinaY1ActionPerformed(evt);
            }
        });

        jLabel24.setText("Rey");

        txtReyX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReyX1ActionPerformed(evt);
            }
        });

        txtReyY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReyY1ActionPerformed(evt);
            }
        });

        jLabel25.setText("Peon");

        txtPeonX9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX9ActionPerformed(evt);
            }
        });

        txtPeonY9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY9ActionPerformed(evt);
            }
        });

        jLabel26.setText("Peon");

        txtPeonX10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX10ActionPerformed(evt);
            }
        });

        txtPeonY10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY10ActionPerformed(evt);
            }
        });

        jLabel27.setText("Pieza");

        jLabel28.setText("X");

        jLabel29.setText("Y");

        jLabel30.setText("Peon");

        txtPeonX11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX11ActionPerformed(evt);
            }
        });

        txtPeonY11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY11ActionPerformed(evt);
            }
        });

        jLabel31.setText("Peon");

        txtPeonX12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX12ActionPerformed(evt);
            }
        });

        txtPeonY12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY12ActionPerformed(evt);
            }
        });

        jLabel32.setText("Peon");

        txtPeonX13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX13ActionPerformed(evt);
            }
        });

        txtPeonY13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY13ActionPerformed(evt);
            }
        });

        jLabel33.setText("Peon");

        txtPeonX14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX14ActionPerformed(evt);
            }
        });

        txtPeonY14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY14ActionPerformed(evt);
            }
        });

        jLabel34.setText("Peon");

        txtPeonX15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX15ActionPerformed(evt);
            }
        });

        txtPeonY15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY15ActionPerformed(evt);
            }
        });

        jLabel35.setText("Peon");

        txtPeonX16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonX16ActionPerformed(evt);
            }
        });

        txtPeonY16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPeonY16ActionPerformed(evt);
            }
        });

        jLabel36.setText("Pieza");

        jLabel37.setText("X");

        jLabel38.setText("Y");

        jLabel39.setText("Torre");

        txtTorreX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreX3ActionPerformed(evt);
            }
        });

        txtTorreY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreY3ActionPerformed(evt);
            }
        });

        jLabel40.setText("Torre");

        txtTorreX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreX4ActionPerformed(evt);
            }
        });

        jLabel41.setText("Caballo");

        txtCaballoX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoX3ActionPerformed(evt);
            }
        });

        txtCaballoY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoY3ActionPerformed(evt);
            }
        });

        jLabel42.setText("Caballo");

        txtCaballoX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoX4ActionPerformed(evt);
            }
        });

        txtCaballoY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCaballoY4ActionPerformed(evt);
            }
        });

        jLabel43.setText("Alfil");

        txtAlfilX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilX3ActionPerformed(evt);
            }
        });

        txtAlfilY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilY3ActionPerformed(evt);
            }
        });

        jLabel44.setText("Alfil");

        txtAlfilX4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilX4ActionPerformed(evt);
            }
        });

        txtAlfilY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlfilY4ActionPerformed(evt);
            }
        });

        txtTorreY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTorreY4ActionPerformed(evt);
            }
        });

        jLabel45.setText("Reina");

        txtReinaX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReinaX2ActionPerformed(evt);
            }
        });

        txtReinaY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReinaY2ActionPerformed(evt);
            }
        });

        jLabel46.setText("Rey");

        txtReyX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReyX2ActionPerformed(evt);
            }
        });

        txtReyY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReyY2ActionPerformed(evt);
            }
        });

        btnJugar.setText("Jugar!");
        btnJugar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJugarMouseClicked(evt);
            }
        });
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel15)
                                        .addGap(96, 96, 96)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel5)
                                                .addGap(14, 14, 14))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtPeonX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(txtPeonY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel7)
                                                    .addGap(71, 71, 71))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtPeonX3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtPeonY3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel8)
                                                        .addGap(71, 71, 71))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(txtPeonX4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(txtPeonY4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addComponent(jLabel9)
                                                            .addGap(71, 71, 71))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtPeonX5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtPeonY5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(71, 71, 71))
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(layout.createSequentialGroup()
                                                                    .addComponent(txtPeonX6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                    .addComponent(txtPeonY6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                    .addComponent(jLabel11)
                                                                    .addGap(71, 71, 71))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(txtPeonX7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtPeonY7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                        .addComponent(jLabel12)
                                                                        .addGap(71, 71, 71))
                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                            .addGap(61, 61, 61)
                                                                            .addComponent(txtPeonX8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                            .addComponent(txtPeonY8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                            .addComponent(jLabel13)
                                                                            .addGap(71, 71, 71)))))))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtPeonX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPeonY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAlfilX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtAlfilY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addComponent(txtTorreX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTorreY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(113, 113, 113)
                                            .addComponent(jLabel16)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCaballoX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCaballoY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel24))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtReyX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtReyY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtReinaX1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtReinaY1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtAlfilX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAlfilY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTorreX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCaballoX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCaballoY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTorreY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel29)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPeonX11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPeonY10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel30)
                                .addComponent(jLabel27))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel26)))))))
                                .addGap(2, 2, 2)))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel37))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtTorreX3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTorreY4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel38)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtCaballoX3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtCaballoY3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtAlfilX3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtAlfilY3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtReyX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtReyY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtReinaX2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtReinaY2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtAlfilX4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtAlfilY4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTorreX4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCaballoX4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCaballoY4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTorreY3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel36)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel41, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel43)
                                        .addComponent(jLabel45)
                                        .addComponent(jLabel46)
                                        .addComponent(jLabel44)
                                        .addComponent(jLabel40))
                                    .addGap(481, 481, 481)))
                            .addComponent(jLabel42)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJugar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPeonX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTorreY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(txtTorreX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPeonX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)
                            .addComponent(txtCaballoY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaballoX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtPeonX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(txtAlfilY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlfilX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtPeonX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(txtReinaY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReinaX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txtPeonX5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPeonY5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel24)
                                .addComponent(txtReyY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtReyX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPeonX6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(txtAlfilY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlfilX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtPeonX7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtCaballoY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaballoX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtPeonX8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTorreY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtTorreX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(jLabel28)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(txtPeonX11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(txtPeonX12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(txtPeonX13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txtPeonX14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(txtPeonX15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(txtPeonX16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtPeonX9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txtPeonX10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPeonY9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel36)
                                .addComponent(jLabel37)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTorreY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)
                            .addComponent(txtTorreX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel41)
                            .addComponent(txtCaballoY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaballoX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel43)
                            .addComponent(txtAlfilY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlfilX3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(txtReinaY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReinaX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(txtReyY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReyX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtAlfilY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlfilX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(txtCaballoY4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCaballoX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTorreY3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addComponent(txtTorreX4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPeonX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX1ActionPerformed

    private void txtTorreY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreY1ActionPerformed

    private void txtPeonY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY2ActionPerformed

    private void txtPeonX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX2ActionPerformed

    private void txtPeonY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY3ActionPerformed

    private void txtPeonX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX3ActionPerformed

    private void txtPeonY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY4ActionPerformed

    private void txtPeonX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX4ActionPerformed

    private void txtPeonY5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY5ActionPerformed

    private void txtPeonX5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX5ActionPerformed

    private void txtPeonY6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY6ActionPerformed

    private void txtPeonX6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX6ActionPerformed

    private void txtPeonY7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY7ActionPerformed

    private void txtPeonX7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX7ActionPerformed

    private void txtPeonY8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY8ActionPerformed

    private void txtPeonX8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX8ActionPerformed

    private void txtTorreX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreX1ActionPerformed

    private void txtPeonY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY1ActionPerformed

    private void txtTorreY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreY2ActionPerformed

    private void txtTorreX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreX2ActionPerformed

    private void txtCaballoX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoX1ActionPerformed

    private void txtCaballoY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoY1ActionPerformed

    private void txtCaballoX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoX2ActionPerformed

    private void txtCaballoY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoY2ActionPerformed

    private void txtAlfilX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilX1ActionPerformed

    private void txtAlfilY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilY1ActionPerformed

    private void txtAlfilX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilX2ActionPerformed

    private void txtAlfilY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilY2ActionPerformed

    private void txtReinaX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReinaX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReinaX1ActionPerformed

    private void txtReinaY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReinaY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReinaY1ActionPerformed

    private void txtReyX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReyX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReyX1ActionPerformed

    private void txtReyY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReyY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReyY1ActionPerformed

    private void txtPeonX9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX9ActionPerformed

    private void txtPeonY9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY9ActionPerformed

    private void txtPeonX10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX10ActionPerformed

    private void txtPeonY10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY10ActionPerformed

    private void txtPeonX11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX11ActionPerformed

    private void txtPeonY11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY11ActionPerformed

    private void txtPeonX12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX12ActionPerformed

    private void txtPeonY12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY12ActionPerformed

    private void txtPeonX13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX13ActionPerformed

    private void txtPeonY13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY13ActionPerformed

    private void txtPeonX14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX14ActionPerformed

    private void txtPeonY14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY14ActionPerformed

    private void txtPeonX15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX15ActionPerformed

    private void txtPeonY15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY15ActionPerformed

    private void txtPeonX16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonX16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonX16ActionPerformed

    private void txtPeonY16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPeonY16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPeonY16ActionPerformed

    private void txtTorreX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreX3ActionPerformed

    private void txtTorreY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreY3ActionPerformed

    private void txtTorreX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreX4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreX4ActionPerformed

    private void txtCaballoX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoX3ActionPerformed

    private void txtCaballoY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoY3ActionPerformed

    private void txtCaballoX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoX4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoX4ActionPerformed

    private void txtCaballoY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCaballoY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaballoY4ActionPerformed

    private void txtAlfilX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilX3ActionPerformed

    private void txtAlfilY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilY3ActionPerformed

    private void txtAlfilX4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilX4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilX4ActionPerformed

    private void txtAlfilY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlfilY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlfilY4ActionPerformed

    private void txtTorreY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTorreY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTorreY4ActionPerformed

    private void txtReinaX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReinaX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReinaX2ActionPerformed

    private void txtReinaY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReinaY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReinaY2ActionPerformed

    private void txtReyX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReyX2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReyX2ActionPerformed

    private void txtReyY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReyY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReyY2ActionPerformed

    private void btnJugarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugarMouseClicked
        this.gameCtrl = new GameController();
        gameCtrl.InitializeGame(true, Integer.parseInt(txtPlayer1.getText()), Integer.parseInt(txtPlayer2.getText()));
        ShowPiecesPositions();
    }//GEN-LAST:event_btnJugarMouseClicked

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed

    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAlfilX1;
    private javax.swing.JTextField txtAlfilX2;
    private javax.swing.JTextField txtAlfilX3;
    private javax.swing.JTextField txtAlfilX4;
    private javax.swing.JTextField txtAlfilY1;
    private javax.swing.JTextField txtAlfilY2;
    private javax.swing.JTextField txtAlfilY3;
    private javax.swing.JTextField txtAlfilY4;
    private javax.swing.JTextField txtCaballoX1;
    private javax.swing.JTextField txtCaballoX2;
    private javax.swing.JTextField txtCaballoX3;
    private javax.swing.JTextField txtCaballoX4;
    private javax.swing.JTextField txtCaballoY1;
    private javax.swing.JTextField txtCaballoY2;
    private javax.swing.JTextField txtCaballoY3;
    private javax.swing.JTextField txtCaballoY4;
    private javax.swing.JTextField txtPeonX1;
    private javax.swing.JTextField txtPeonX10;
    private javax.swing.JTextField txtPeonX11;
    private javax.swing.JTextField txtPeonX12;
    private javax.swing.JTextField txtPeonX13;
    private javax.swing.JTextField txtPeonX14;
    private javax.swing.JTextField txtPeonX15;
    private javax.swing.JTextField txtPeonX16;
    private javax.swing.JTextField txtPeonX2;
    private javax.swing.JTextField txtPeonX3;
    private javax.swing.JTextField txtPeonX4;
    private javax.swing.JTextField txtPeonX5;
    private javax.swing.JTextField txtPeonX6;
    private javax.swing.JTextField txtPeonX7;
    private javax.swing.JTextField txtPeonX8;
    private javax.swing.JTextField txtPeonX9;
    private javax.swing.JTextField txtPeonY1;
    private javax.swing.JTextField txtPeonY10;
    private javax.swing.JTextField txtPeonY11;
    private javax.swing.JTextField txtPeonY12;
    private javax.swing.JTextField txtPeonY13;
    private javax.swing.JTextField txtPeonY14;
    private javax.swing.JTextField txtPeonY15;
    private javax.swing.JTextField txtPeonY16;
    private javax.swing.JTextField txtPeonY2;
    private javax.swing.JTextField txtPeonY3;
    private javax.swing.JTextField txtPeonY4;
    private javax.swing.JTextField txtPeonY5;
    private javax.swing.JTextField txtPeonY6;
    private javax.swing.JTextField txtPeonY7;
    private javax.swing.JTextField txtPeonY8;
    private javax.swing.JTextField txtPeonY9;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    private javax.swing.JTextField txtReinaX1;
    private javax.swing.JTextField txtReinaX2;
    private javax.swing.JTextField txtReinaY1;
    private javax.swing.JTextField txtReinaY2;
    private javax.swing.JTextField txtReyX1;
    private javax.swing.JTextField txtReyX2;
    private javax.swing.JTextField txtReyY1;
    private javax.swing.JTextField txtReyY2;
    private javax.swing.JTextField txtTorreX1;
    private javax.swing.JTextField txtTorreX2;
    private javax.swing.JTextField txtTorreX3;
    private javax.swing.JTextField txtTorreX4;
    private javax.swing.JTextField txtTorreY1;
    private javax.swing.JTextField txtTorreY2;
    private javax.swing.JTextField txtTorreY3;
    private javax.swing.JTextField txtTorreY4;
    // End of variables declaration//GEN-END:variables

    private void ShowPiecesPositions() {
        List<Piece> WhitePieces = gameCtrl.getGame().getWhite().getPieces();
        txtPeonX1.setText(String.valueOf(WhitePieces.get(0).getX()));
        txtPeonY1.setText(String.valueOf(WhitePieces.get(0).getY()));
    }
}
