/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desktop;

import Logic.GameController;
import Models.Piece;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jjdelannoy
 */
public class TableroGrilla extends javax.swing.JFrame {
    private GameController gameCtrl;
    private Models.Game game;
    /**
     * Creates new form TableroGrilla
     */
    public TableroGrilla() {
        initComponents();
    }
    
    public TableroGrilla(Models.Game game) throws SQLException {
        initComponents();
        this.game = game;
         this.gameCtrl = new GameController();
            gameCtrl.LoadSavedGame(this.game);
            ShowPiecesPositions();
            LoadComboBoxPieces();
            txtPlayer1.setText(String.valueOf(game.getWhite().getDni()));
            txtPlayer2.setText(String.valueOf(game.getBlack().getDni()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBlack = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableWhite = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPlayer1 = new javax.swing.JTextField();
        txtPlayer2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbWhitePlayer = new javax.swing.JComboBox();
        txtWhiteX = new javax.swing.JTextField();
        txtWhiteY = new javax.swing.JTextField();
        cmbBlackPlayer = new javax.swing.JComboBox();
        txtBlackX = new javax.swing.JTextField();
        txtBlackY = new javax.swing.JTextField();
        btnBlackMove = new javax.swing.JButton();
        btnWhiteMove = new javax.swing.JButton();
        btnJugar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableBlack.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ficha", "X", "Y"
            }
        ));
        jScrollPane1.setViewportView(tableBlack);

        tableWhite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Ficha", "X", "Y"
            }
        ));
        jScrollPane2.setViewportView(tableWhite);

        btnSave.setText("Guardar Partida");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Jugador 1");

        txtPlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayer1ActionPerformed(evt);
            }
        });

        txtPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayer2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Jugador 2");

        cmbWhitePlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbWhitePlayer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWhitePlayerItemStateChanged(evt);
            }
        });

        cmbBlackPlayer.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBlackPlayer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbBlackPlayerItemStateChanged(evt);
            }
        });

        txtBlackX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBlackXActionPerformed(evt);
            }
        });

        btnBlackMove.setText("Mover");
        btnBlackMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBlackMoveMouseClicked(evt);
            }
        });

        btnWhiteMove.setText("Mover");
        btnWhiteMove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnWhiteMoveMouseClicked(evt);
            }
        });

        btnJugar1.setText("Jugar!");
        btnJugar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnJugar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cmbWhitePlayer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWhiteX, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtWhiteY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnWhiteMove, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnJugar1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbBlackPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(txtBlackX, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBlackY, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBlackMove, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbWhitePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtWhiteX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtWhiteY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnWhiteMove)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbBlackPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnJugar1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBlackX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBlackY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBlackMove))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayer1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayer1ActionPerformed

    private void txtPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayer2ActionPerformed

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if(txtPlayer1.getText().isEmpty() || txtPlayer2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese Los DNI de los Jugadores");
        }
        else{
            this.gameCtrl.saveGame(Integer.parseInt(txtPlayer1.getText()), Integer.parseInt(txtPlayer2.getText()));
        };
        JOptionPane.showMessageDialog(null, "Partida Guardada!");

        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnBlackMoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBlackMoveMouseClicked
        MakeMovement((Piece)cmbBlackPlayer.getSelectedItem(), Integer.parseInt(txtBlackX.getText()), Integer.parseInt(txtBlackY.getText()));
    }//GEN-LAST:event_btnBlackMoveMouseClicked

    private void btnWhiteMoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWhiteMoveMouseClicked
        MakeMovement((Piece)cmbWhitePlayer.getSelectedItem(), Integer.parseInt(txtWhiteX.getText()), Integer.parseInt(txtWhiteY.getText()));
    }//GEN-LAST:event_btnWhiteMoveMouseClicked

    private void txtBlackXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBlackXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBlackXActionPerformed

    private void cmbWhitePlayerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWhitePlayerItemStateChanged
        Piece piece = (Piece)cmbWhitePlayer.getSelectedItem();
        txtWhiteX.setText(String.valueOf(piece.getX()));
        txtWhiteY.setText(String.valueOf(piece.getY()));
    }//GEN-LAST:event_cmbWhitePlayerItemStateChanged

    private void cmbBlackPlayerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbBlackPlayerItemStateChanged
        Piece piece = (Piece)cmbBlackPlayer.getSelectedItem();
        txtBlackX.setText(String.valueOf(piece.getX()));
        txtBlackY.setText(String.valueOf(piece.getY()));
    }//GEN-LAST:event_cmbBlackPlayerItemStateChanged

    private void btnJugar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnJugar1MouseClicked
        if(txtPlayer1.getText().isEmpty() || txtPlayer2.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese Los DNI de los Jugadores");
        }
        else{
            this.gameCtrl = new GameController();
            gameCtrl.InitializeGame(true, Integer.parseInt(txtPlayer1.getText()), Integer.parseInt(txtPlayer2.getText()));
            ShowPiecesPositions();
            LoadComboBoxPieces();
        };
    }//GEN-LAST:event_btnJugar1MouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableroGrilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableroGrilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableroGrilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableroGrilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableroGrilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBlackMove;
    private javax.swing.JButton btnJugar1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnWhiteMove;
    private javax.swing.JComboBox cmbBlackPlayer;
    private javax.swing.JComboBox cmbWhitePlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableBlack;
    private javax.swing.JTable tableWhite;
    private javax.swing.JTextField txtBlackX;
    private javax.swing.JTextField txtBlackY;
    private javax.swing.JTextField txtPlayer1;
    private javax.swing.JTextField txtPlayer2;
    private javax.swing.JTextField txtWhiteX;
    private javax.swing.JTextField txtWhiteY;
    // End of variables declaration//GEN-END:variables

     private void ShowPiecesPositions() {
        Object columnNames[] = { "Fichas", "X", "Y" };
        DefaultTableModel whiteModel = new DefaultTableModel(columnNames, 0);
         DefaultTableModel blackModel = new DefaultTableModel(columnNames, 0);
        List<Piece> WhitePieces = gameCtrl.getGame().getWhite().getPiecesAviables();
        for (Piece piece : WhitePieces) {
              Object rowData[] = { piece.getClass().getName() , String.valueOf(piece.getX()), String.valueOf(piece.getY()) };
              whiteModel.addRow(rowData);
        }
        tableWhite.setModel(whiteModel);
        
         List<Piece> BlackPieces = gameCtrl.getGame().getBlack().getPiecesAviables();
        for (Piece piece : BlackPieces) {
              Object rowData[] = { piece.getClass().getName() , String.valueOf(piece.getX()), String.valueOf(piece.getY()) };
              blackModel.addRow(rowData);
        }
        tableBlack.setModel(blackModel);
    }

    private void LoadComboBoxPieces() {
        cmbWhitePlayer.setModel(new DefaultComboBoxModel(this.gameCtrl.getGame().getWhite().getPiecesAviables().toArray()));
        cmbBlackPlayer.setModel(new DefaultComboBoxModel(this.gameCtrl.getGame().getBlack().getPiecesAviables().toArray()));
        Piece pieceWhite = (Piece)cmbWhitePlayer.getSelectedItem();
        txtWhiteX.setText(String.valueOf(pieceWhite.getX()));
        txtWhiteY.setText(String.valueOf(pieceWhite.getY()));
        Piece pieceBlack = (Piece)cmbBlackPlayer.getSelectedItem();
        txtBlackX.setText(String.valueOf(pieceBlack.getX()));
        txtBlackY.setText(String.valueOf(pieceBlack.getY()));
       // cmbStoredGames.setModel(new DefaultComboBoxModel(getStoredGames().toArray()));
    }
    
    private void MakeMovement(Piece piece, int toX, int toY) {
        String[] response = this.gameCtrl.MakeMovement(piece, toX, toY);
        switch (response[0]){
            case "1": 
                JOptionPane.showMessageDialog(null, response[1]);
                break;
            case "2": 
                JOptionPane.showMessageDialog(null, response[1]);
                break;
            case "3":
                Object ob = this.gameCtrl.getGame().getWhite().getPieces();
                RealoadDashBoard();
                break;
        }
        
    }

    private void RealoadDashBoard() {
        ShowPiecesPositions();
        LoadComboBoxPieces();
    }


}
